name: Main
on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ["windows-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Build with py2exe
        run: |
          python -m pip install -r requirements.txt
  publish:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Publish
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
