name: Main
on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  schedule:
  - cron: '* * * * *'
jobs:
  build:
    runs-on: ["windows-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Test Requirements
        run: |
          python -m pip install -r requirements.txt
  publish:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Publish
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  github-metrics:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          user: TurnipGuy30
          repo: Jupyter
          template: repository
